# Ask TravisCI to build the site for testing purposes,
# results at https://travis-ci.org/biopython/biopython.github.io/builds
# See https://help.github.com/articles/troubleshooting-github-pages-build-failures/

language: ruby
rvm: 2.1.1
script: "bundle exec jekyll build"
