# Ask TravisCI to build the site for testing purposes,
# results at https://travis-ci.org/biopython/biopython.github.io/builds
# See https://help.github.com/articles/troubleshooting-github-pages-build-failures/
#
# We ask TravisCI to use the same version of Ruby as used on GitHub Pages,
# see https://docs.travis-ci.com/user/languages/ruby/ and
# https://pages.github.com/versions/

language: ruby
rvm: 2.1.7
script:
 - "if grep '\t' wiki/*.md; then echo 'Tabs are bad, please use four spaces.'; false; fi"
 - "bundle exec jekyll build"
