# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Setup
title: Biopython
tagline: Python Tools for Computational Molecular Biology
url: http://biopython.org
baseurl: /

author:
  name: Biopython Contributors
  url: https://twitter.com/biopython

# Custom variables for Hyde theme
version: "1.72"
github:
  repo: https://github.com/biopython/biopython
