# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Setup
title: Biopython
tagline: Python Tools for Computational Molecular Biology
url: http://biopython.org
baseurl:

author:
  name: Biopython Contributors
  url: https://biopython.org

# Custom variables for Hyde theme
version: "1.84"
github:
  repo: https://github.com/biopython/biopython
