# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Setup
title: Biopython
tagline: Python Tools for Computational Molecular Biology
url: http://biopython.org
baseurl: /

author:
  name: Biopython Contributors
  url: https://twitter.com/biopython

# Page settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# Custom variables for Hyde theme
version: 1.66
github:
  repo: https://github.com/biopython/biopython
